defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.5

android-defaults: &android-defaults
  working_directory: ~/repo
  docker:
    - image: karrot/android-build:api-27-node8-alpha

build-android: &build-android
  name: build android
  command: |
    rm -f cordova/www
    mv dist-app-${CORDOVA_ENV} cordova/www
    cd ~/repo/cordova
    rm -f config/current
    ln -s "$CORDOVA_ENV" config/current
    cordova platform add android
    ./build android "$CORDOVA_ENV" release "${!PASSWORD_VAR}"
    mv platforms/android/build/outputs/apk/release/android-release.apk ~/repo/android-${CORDOVA_ENV}.apk

ios-defaults: &ios-defaults
  working_directory: ~/repo
  macos:
    xcode: "9.2.0"
  shell: /bin/bash --login -eo pipefail

prepare-build-ios: &prepare-build-ios
  command: |
    rm -f cordova/www
    mv dist-app-${CORDOVA_ENV} cordova/www
    cd ~/repo/cordova
    rm -f config/current
    ln -s "${CORDOVA_ENV}" config/current
    cordova platform add ios

version: 2
jobs:

  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  install-fastlane-dependencies:
    <<: *ios-defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/
      - restore_cache:
          key: 1-fastlane-dependencies-{{ checksum "cordova/Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/cordova
      - save_cache:
          paths:
            - vendor/cordova
          key: 1-fastlane-dependencies-{{ checksum "cordova/Gemfile.lock" }}

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn test --ci --runInBand
      - run: bash <(curl -s https://codecov.io/bash)

  install-e2e-dependencies:
    working_directory: ~/repo
    docker:
      - image: karrot/e2e:1.1
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: python-cache
      - run:
          name: prepare backend
          command: |
            set -x
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            git clone https://github.com/yunity/karrot-backend
            cd karrot-backend
            virtualenv -p python3 env
            env/bin/pip install --upgrade pip
            env/bin/pip install pip-tools
            env/bin/pip-sync requirements*.txt
            cp config/local_settings.py.ci config/local_settings.py
      - save_cache:
          paths:
            - env
            - ~/.cache/pip
          key: python-cache
      - persist_to_workspace:
          root: ~/repo
          paths:
            - karrot-backend/*

  e2e-test:
    working_directory: ~/repo
    docker:
      - image: karrot/e2e:1.1
        environment:
          PGHOST: 127.0.0.1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: fstool_e2etest
      - image: redis:3.2.11
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: run backend
          command: |
            set -x
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            cd karrot-backend
            env/bin/python manage.py migrate
            env/bin/python manage.py runserver
          background: true
      - run:
          name: run frontend
          command: yarn serve
          background: true
      - run:
          name: wait for frontend to get ready
          command: wget --retry-connrefused -T 30 http://localhost:8080
      - run:
          name: wait for backend to get ready
          command: wget --retry-connrefused -T 30 http://localhost:8000/api/groups-info/
      - run:
          name: list all available browsers for your personal benefit
          command: $(yarn bin)/testcafe -b saucelabs
          background: true
      - run:
          name: testcafe
          command: yarn e2e --ci

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn lint

  build-dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          environment:
            KARROT_THEME: dev
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  build-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  build-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build-storybook
      - persist_to_workspace:
          root: ~/repo
          paths:
            - storybook-static

  build-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build docs
          command: |
            set +e
            yarn build-docs
      - persist_to_workspace:
          root: ~/repo
          paths:
            - docs-dist

  build-cordova-dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build cordova app
          command: |
            yarn build:cordova:dev
            mv dist dist-app-dev
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist-app-dev

  build-cordova-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build cordova app
          command: |
            yarn build:cordova:prod
            mv dist dist-app-prod
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist-app-prod

  build-android-dev:
    <<: *android-defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - gradle-cache
      - run:
          <<: *build-android
          name: build android apk
          environment:
            CORDOVA_ENV: dev
            PASSWORD_VAR: CORDOVA_DEV_PASSWORD
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache
      - persist_to_workspace:
          root: ~/repo
          paths:
            - android-dev.apk

  deploy-android-dev:
    <<: *defaults
    steps:
      - run: sudo apt install -y rsync
      - attach_workspace:
          at: .
      - run:
          name: deploy apk
          command: |
            ./deploy-android.sh "${CIRCLE_BRANCH}" android-dev.apk "${CIRCLE_BRANCH}"

  deploy-android-prod:
    <<: *defaults
    steps:
      - run: sudo apt install -y rsync
      - attach_workspace:
          at: .
      - run:
          name: deploy apk
          command: |
            ./deploy-android.sh "${CIRCLE_BRANCH}" android-prod.apk release

  build-android-prod:
    <<: *android-defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
          - gradle-cache
      - run:
          <<: *build-android
          name: build android apk
          environment:
            CORDOVA_ENV: prod
            PASSWORD_VAR: CORDOVA_PROD_PASSWORD
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache
      - persist_to_workspace:
          root: ~/repo
          paths:
            - android-prod.apk

  build-ios-dev:
    <<: *ios-defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn global add cordova
      - run:
          <<: *prepare-build-ios
          environment:
            CORDOVA_ENV: dev
      - run:
          command: |
            export LC_ALL=C.UTF-8
            export LANG=C.UTF-8
            fastlane test
          environment:
            GYM_WORKSPACE: platforms/ios/Karrot Dev.xcworkspace
            APPLE_ID: IOS_APPLE_ID

  deploy-dev:
    <<: *defaults
    steps:
      - run: sudo apt install -y rsync
      - checkout
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Dev Deploy
          command: |
            ./deploy.sh "${CIRCLE_BRANCH}" "${CIRCLE_BRANCH}"

  deploy-release:
    <<: *defaults
    steps:
      - run: sudo apt install -y rsync
      - checkout
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Release Deploy
          command: |
            ./deploy.sh "${CIRCLE_BRANCH}" release

workflows:
  version: 2
  all-the-things:
    jobs:
      - install-dependencies
      - test:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - lint:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - build-dev:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - build-storybook:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - build-docs:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - master
      - build-cordova-dev:
          requires:
            - install-dependencies
      - build-android-dev:
          requires:
            - build-cordova-dev
          filters:
            branches:
              only:
                - master
      - build-ios-dev:
          requires:
            - build-cordova-dev
            - install-fastlane-dependencies
      - deploy-android-dev:
          filters:
            branches:
              only:
                - master
          requires:
            - build-android-dev
            - test
      - deploy-dev:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - lint
            - build-dev
            - build-storybook
            - build-docs
      - approval:
          type: approval
          requires:
            - deploy-dev
      - build-prod:
          requires:
            - approval
      - build-cordova-prod:
          requires:
            - approval
      - build-android-prod:
          requires:
            - build-cordova-prod
      - install-e2e-dependencies:
          requires:
            - build-prod
      - e2e-test:
          requires:
            - install-e2e-dependencies
      - deploy-android-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build-android-prod
            - e2e-test
      - deploy-release:
          filters:
            branches:
              only:
                - master
          requires:
            - e2e-test
